Level/abstract-level

- abstract-level.js
When compared to `level@7` and friends.
Ref https://github.com/Level/abstract-level/issues/4#issuecomment-1024703508
Ref https://bugs.chromium.org/p/chromium/issues/detail?id=1204540
> Use `Object.assign()` to avoid performance regression

- README.md
Ref https://github.com/Level/classic-level/pull/8
> Document error codes of `classic-level` and `many-level`

- README.md
- UPGRADING.md
- abstract-chained-batch.js
- abstract-iterator.js
- abstract-level.js
- index.d.ts
- lib/abstract-sublevel.js
- lib/common.js
- lib/default-chained-batch.js
- lib/event-monitor.js
- lib/hooks.js
- lib/prefixes.js
- lib/prewrite-batch.js
- package.json
- test/batch-test.js
- test/events/write.js
- test/hooks/newsub.js
- test/hooks/postopen.js
- test/hooks/prewrite.js
- test/hooks/shared.js
- test/index.js
- test/self.js
- test/self/encoding-test.js
- test/self/sublevel-test.js
- test/sublevel-test.js
- types/abstract-level.d.ts
- types/abstract-sublevel.d.ts
Adds postopen, prewrite and newsub hooks that allow userland "hook functions" to customize behavior of the database. See [README for details](https://github.com/Level/abstract-level/tree/hooks#hooks). A quick example:
```js
db.hooks.prewrite.add(function (op, batch) {
if (op.type === 'put') {
batch.add({
type: 'put',
key: op.value.foo,
value: op.key,
sublevel: fooIndex
})
}
})
```
More generally, this is a move towards "renewed modularity". Our ecosystem is old and many modules no longer work because they had no choice but to monkeypatch database methods, of which the signature has changed since then.
So in addition to hooks, this:
- [Introduces a new `write` event](https://github.com/Level/abstract-level/tree/hooks#events) that is emitted on `db.batch()`, `db.put()` and `db.del()` and …
> Add hooks and deprecate `batch`, `put` & `del` events

- README.md
Follow-up for https://github.com/Level/abstract-level/pull/45.
> Mark hooks as experimental

- README.md
- UPGRADING.md
Ref https://github.com/Level/community/issues/118.
> Breaking: require snapshots to be created synchronously

- test/sublevel-test.js
Follow-up for #51. Found while testing v2 on `memory-level` (#57).
> Avoid chained batch in deferred test

- README.md
- abstract-iterator.js
- test/iterator-seek-test.js
- test/iterator-test.js
- test/self/abstract-iterator-test.js
- test/self/iterator-test.js
- test/util.js
> Keep track of iterator end

- README.md
- lib/errors.js
- package.json
- test/iterator-test.js
Depends on https://github.com/Level/supports/pull/22. Otherwise complete.
> Add opt-in test for `signal` option

- README.md
- UPGRADING.md
- lib/abstract-sublevel.js
- test/self/sublevel-test.js
- types/abstract-sublevel.d.ts
> Expose path of sublevel

- README.md
- UPGRADING.md
- abstract-chained-batch.js
- abstract-level.js
- lib/prefixes.js
- lib/prewrite-batch.js
- test/hooks/prewrite.js
- test/sublevel-test.js
Closes #80. Follow-up for #45.
> Allow batches to write to a nondescendant sublevel

- test/hooks/prewrite.js
Ref: https://github.com/Level/memory-level/pull/10
> Generalize prewrite test for memory-level

- README.md
This is a documentation-only PR, acting as an RFC. I opted for a token-based approach (as suggested by Rod Vagg in https://github.com/Level/community/issues/45) instead of a dedicated snapshot API surface (as suggested by @juliangruber in https://github.com/Level/community/issues/47). Main reasons for not choosing the latter:
- It would be a third API surface. We have the main database API surface which is roughly equal to that of a sublevel, and would now add another API surface which only has read methods, e.g. `db.snapshot().get()`. If you could pass around a snapshot as if it was a regular database (like you can with sublevels) then I'd be cool with it. But for that to happen, we'd have to implement write methods and thus transactions as well, which I consider to be out of scope …
> Add explicit snapshots to README

- README.md
- abstract-iterator.js
- abstract-level.js
- abstract-snapshot.js
- index.d.ts
- index.js
- lib/abstract-sublevel.js
- package.json
- test/async-iterator-test.js
- test/index.js
- test/iterator-explicit-snapshot-test.js
- test/iterator-seek-test.js
- test/traits/closed.js
- test/traits/open.js
- test/util.js
- types/abstract-level.d.ts
- types/abstract-snapshot.d.ts
See https://github.com/Level/community/issues/118. TLDR:
```js
await db.put('example', 'before')
const snapshot = db.snapshot()
await db.put('example', 'after')
await db.get('example', { snapshot })) // Returns 'before'
await snapshot.close()
```
> Implement explicit snapshots

- README.md
- abstract-chained-batch.js
- abstract-iterator.js
- abstract-level.js
- abstract-snapshot.js
- test/chained-batch-test.js
- test/iterator-explicit-snapshot-test.js
- test/iterator-test.js
- test/open-test.js
- types/abstract-chained-batch.d.ts
- types/abstract-iterator.d.ts
- types/abstract-level.d.ts
- types/abstract-snapshot.d.ts
Per [`proposal-explicit-resource-management`](https://github.com/tc39/proposal-explicit-resource-management) which in TypeScript (5.2) allows you to skip calling `.close()`:
```ts
await db.put('example', 'before')
await using snapshot = db.snapshot()
await db.put('example', 'after')
await db.get('example', { snapshot })) // Returns 'before'
```
Works on databases, iterators, snapshots and batches.
> Implement `Symbol.asyncDispose`

- README.md
- abstract-level.js
- lib/abstract-sublevel.js
- package.json
- test/has-many-test.js
- test/has-test.js
- test/index.js
- test/util.js
- types/abstract-level.d.ts
Adds two methods:
```js
await db.put('love', 'u')
await db.has('love') // true
await db.hasMany(['love', 'hate']) // [true, false]
```
Ref: https://github.com/Level/community/issues/142
> Implement `has()` and `hasMany()`

- README.md
- index.d.ts
- types/abstract-iterator.d.ts
- types/abstract-level.d.ts
- types/interfaces.d.ts
Just tweaks:
- Add `snapshot` to TypeScript option types
- Remove redundant documentation from README
- Don't mark explicit snapshots as experimental. I'm confident in this feature now (having finished the implementation in `classic-level`) and I'm happy with the API.
Ref: https://github.com/Level/community/issues/118
Follow-Up-To: https://github.com/Level/abstract-level/pull/93
> Improve snapshot documentation

- .airtap.yml
- .github/dependabot.yml
- abstract-chained-batch.js
- abstract-iterator.js
- abstract-level.js
- abstract-snapshot.js
- lib/abstract-sublevel-iterator.js
- lib/abstract-sublevel.js
- lib/default-chained-batch.js
- lib/deferred-queue.js
- lib/hooks.js
- lib/prewrite-batch.js
- package.json
Namely private properties, optional chaining and the nullish coalescing operator. This is a syntactic refactoring that makes no difference for most consumers. The syntax is supported by all our target environments, but if browserify is used (without babel or similar) it'll fail to parse.
> Breaking: use new language features

- README.md
- lib/abstract-sublevel.js
- test/self/sublevel-test.js
This is a tweak to align state. Operations on the sublevel would already fail with `LEVEL_DATABASE_NOT_OPEN` but `sublevel.status` did not reflect that.
> Close sublevels upon closing parent db

- abstract-chained-batch.js
- abstract-level.js
- lib/prewrite-batch.js
- test/iterator-range-test.js
Because the Chromium bug has been fixed.
Ref: https://bugs.chromium.org/p/chromium/issues/detail?id=1204540
> Refactor: restore use of spread operator

- abstract-chained-batch.js
- abstract-level.js
- lib/prewrite-batch.js
Only matters for implementations that override these methods, and not for end users.
> Breaking: change `_checkKey` and `_checkValue` to assertions

- README.md
- abstract-iterator.js
- abstract-level.js
- test/index.js
- test/self/sublevel-test.js
All first-party implementations already support it (`classic-level`, `memory-level`, `browser-level`, `many-level` and `rave-level`).
> Breaking: make `iterator.seek()` a mandatory feature

- README.md
- abstract-chained-batch.js
- abstract-level.js
- lib/event-monitor.js
- test/batch-test.js
- test/chained-batch-test.js
- test/del-test.js
- test/events/write.js
- test/put-test.js
- test/self/sublevel-test.js
In favor of the `write` event.
While still printing a warning if listeners are added for these events, because it's cheap and helps people who are upgrading.
> Breaking: remove deprecated `put`, `del` & `batch` events

- test/iterator-seek-test.js
Closes a code coverage gap in `memory-level`.
> Test seeking outside of range options

- README.md
Follow-up to #96. I forgot to document the private API.
> Add docs for private `_has()` and `_hasMany()`

- README.md
- abstract-level.js
- lib/abstract-sublevel.js
- test/encoding-buffer-test.js
- test/encoding-custom-test.js
- test/encoding-decode-error-test.js
- test/encoding-json-test.js
- test/encoding-test.js
- test/get-sync-test.js
- test/index.js
- test/iterator-explicit-snapshot-test.js
- test/put-get-del-test.js
- test/util.js
- types/abstract-level.d.ts
Ref https://github.com/Level/community/issues/144
> Add `getSync()` method

- types/abstract-sublevel.d.ts
The getter returns `TDatabase["db"]`--if `TDatabase` is an `AbstractSublevel`--or else `TDatabase` itself.
> Make `AbstractSublevel#db` type more specific
